export const ContentText = `
<h1>Lorem Ipsum Dolor</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut enim diam, commodo vel consequat a, euismod et eros. Duis molestie varius risus, in pharetra nisi porttitor at. Ut quis sapien nec nulla finibus faucibus. In consectetur gravida hendrerit. Aenean sit amet urna id turpis dignissim dignissim vel eu quam. Donec aliquam velit in massa consequat, finibus molestie metus porta. Maecenas nec blandit justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec eu lorem vel eros laoreet fermentum. Pellentesque rhoncus imperdiet neque, eu feugiat mauris semper in. Etiam facilisis luctus urna dictum volutpat. Sed in congue elit. Morbi vestibulum risus at rutrum elementum. Morbi imperdiet libero et orci volutpat tincidunt. Suspendisse facilisis non augue et blandit.</p>

<p>Sed eget justo ex. In faucibus turpis sed ligula venenatis, nec lacinia libero fermentum. Proin sit amet rhoncus nisl. Donec eu quam nec urna commodo tempus quis a quam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Ut blandit sem in finibus dictum. Sed tempor dignissim mauris nec varius. Quisque massa dui, rutrum in lacus vel, dignissim blandit felis. Suspendisse nec ullamcorper justo, sed venenatis leo. Nullam accumsan erat tristique ornare sagittis. Phasellus sagittis rutrum lorem, vel condimentum ligula ornare eu.</p>

<p>Vestibulum pellentesque bibendum orci in aliquam. Ut pharetra turpis cursus imperdiet malesuada. Nam vestibulum dui vitae sem convallis luctus. Maecenas nunc ex, sagittis at nibh sit amet, hendrerit feugiat ex. Integer lorem odio, consequat vitae lobortis vel, posuere at justo. Suspendisse eu cursus diam, in aliquam arcu. In cursus porttitor ante, ac vehicula purus sagittis sit amet. Nullam velit felis, interdum vel nunc eu, scelerisque euismod enim. Aliquam venenatis nunc sed sapien mattis, sodales vulputate tellus vulputate. Donec ut orci velit.</p>

<p>Maecenas vestibulum nibh vitae pharetra commodo. Donec in blandit turpis. Praesent consectetur velit at tellus suscipit, vitae fermentum lacus pharetra. Nulla facilisi. Mauris faucibus vitae libero ac lobortis. Cras at ex quis sapien pulvinar facilisis. Aenean elementum neque sed felis rutrum, id hendrerit ante sollicitudin. Pellentesque laoreet dolor sit amet ligula consequat dapibus. Ut nisl risus, finibus id placerat sit amet, vulputate sed lorem. Suspendisse pulvinar semper sollicitudin. Cras lacus sem, pretium eu porttitor a, porttitor eu sapien. Sed velit mi, imperdiet nec feugiat sed, dictum et turpis. Maecenas lectus nunc, feugiat vitae sagittis et, porttitor quis nisl. Donec tincidunt dolor et nisl accumsan pretium. Maecenas bibendum tincidunt augue, finibus lacinia risus ornare eu.</p>

<p>Quisque dictum sem at sapien convallis, et dapibus leo congue. Aenean imperdiet, lectus nec imperdiet efficitur, lectus felis luctus justo, et tempor orci lorem ac lectus. Suspendisse egestas nunc ut est tempus blandit. Sed aliquet vitae ante vitae aliquam. Duis mauris nulla, finibus nec cursus et, posuere ut quam. Suspendisse quis commodo magna. In hac habitasse platea dictumst. Vivamus dolor risus, tempus a ex et, cursus interdum diam.</p>
`;
